using DG.Tweening;
using Manager;
using System;
using System.Collections.Generic;
using System.Linq;
using UniRx;
using UnityEngine;
using UnityEngine.EventSystems;
using UnityEngine.InputSystem;

namespace GamePlay.Phone
{
    public partial class PhoneControl : MonoBehaviour
    {
        [Header("Phone ê´€ë ¨")] public string phoneName = "None";
        public Camera phoneCamera;
        public Vector2Int phoneVerticalViewPortSize = new Vector2Int(600, 960);
        public Vector2Int phoneHorizonViewPortSize => new Vector2Int(phoneVerticalViewPortSize.y, phoneVerticalViewPortSize.x);

        public SpriteRenderer fadeRenderer;
        public GameObject ChargingPort;
        public PhoneSideButton interfaceGroupOnOffButton;

        private Tween fadeTween; // Fade In&Out ê´€ë ¨ Tween
        
        [Header("App ê´€ë ¨")] 
        public ApplicationControl applicationControl;
        public void Awake()
        {
            { // í…ŒìŠ¤í‹‘ìš© 
                PhoneUtil.Release();
                PhoneUtil.currentPhone = this;
            }
            PhoneUtil.AddPhone(this);

            InteractInit();

            applicationControl.OnAddAppEvent.AddListener(app =>
            {
                var obj = (app as MonoBehaviour)?.gameObject;
                foreach (GameObject rootGameObject in obj.scene.GetRootGameObjects())
                {
                    // ë¯¸ë‹ˆ ê²Œì„ ì”¬ì— ìˆëŠ” ëª¨ë“  ê°ì²´ëŠ” Phone ë ˆì´ì–´ë¥¼ ê°€ì§€ë„ë¡ ë³€ê²½
                    foreach (Transform t in rootGameObject.GetComponentsInChildren<Transform>(true))
                    {
                        t.gameObject.layer = LayerMask.NameToLayer("Phone");
                    }
                }

                // í°ì— appì— ë”°ë¥¸ Render Texture í• ë‹¹
                var phoneViewPort = Instantiate(phoneViewPortPrefab, transform);
                phoneViewPort.MakeTextureObject(app.VerticalResolution);
                phoneViewPort.vertical.spriteRenderer.sprite = phoneVerticalSprite;
                phoneViewPort.horizon.spriteRenderer.sprite = phoneHorizonSprite; // ì„¸ë¡œëŠ” ë‹¤ë¥¸ ì´ë¯¸ì§€ ì‚¬ìš©í•´ì•¼ëœë‹¤.
                phoneViewPort.SetShader(phoneShader);
                phoneViewPort.gameObject.SetActive(false);
                phoneViewPort.name = app.AppName;
                phoneViewPortDictionary.Add(app.AppName, phoneViewPort);
            });
            
            applicationControl.OnAppEvent.AddListener(app =>
            {
                var viewPort = phoneViewPortDictionary[app.AppName];
                ChangeViewPort(viewPort);
            });
            
            applicationControl.OnAppResumeEvent.AddListener(app =>
            {
                var viewPort = phoneViewPortDictionary[app.AppName];
                ChangeViewPort(viewPort);
            });

            // í° ì¹´ë©”ë¼ ìƒì„± & ì…‹íŒ…
            if (phoneCamera == null)
            {
                phoneCamera = Instantiate(Camera.main);
                phoneCamera.name = "Phone Camera";
                phoneCamera.cullingMask = LayerMask.GetMask("Phone");
                var uac = phoneCamera.GetComponent<UnityEngine.Rendering.Universal.UniversalAdditionalCameraData>();
                uac.renderPostProcessing = false;
                Destroy(phoneCamera.GetComponent<AudioListener>());
            }
        }

        public void Start()
        {
            SceneUtil.AsyncAddHome(scene =>
            {
                foreach (GameObject rootGameObject in scene.GetRootGameObjects())
                {
                    var app = rootGameObject.GetComponentInChildren<IPhoneApplication>();
                    if (app != null)
                    {
                        applicationControl.AddApp(app);
                        applicationControl.OpenApp(app);
                    }
                }
            });
        }

        public void Update()
        {
            UIInteract();
        }

        public void OnDestroy()
        {
            foreach (var phoneViewPort in phoneViewPortDictionary.Values)
                phoneViewPort.Release();
        }
    }
    
    // ê¸°íƒ€ íš¨ê³¼
    public partial class PhoneControl
    {
        [Header("ê¸°íƒ€ íš¨ê³¼ ê´€ë ¨")] 
        [Tooltip("í™”ë©´ì— ìƒí˜¸ì‘ìš©ì´ ì•ˆë˜ëŠ” ë¹ˆ ê³µê°„ì„ ëˆŒë €ì„ë•Œ")] public AudioClip emptyClickSound;
        [Tooltip("í•¸ë“œí° ì§„ë™ ì‚¬ìš´ë“œ")]public AudioClip vibrationSound;
        
        public void FadeOut(float duration, Color color, float delay = 0f)
        {
            fadeTween?.Kill();

            var a = fadeRenderer.color.a;
            color.a = a;
            fadeRenderer.color = color;
            fadeTween = fadeRenderer.DOFade(1f, duration).SetDelay(delay);
        }
        
        public void FadeIn(float duration, Color color, float delay = 0f)
        {
            fadeTween?.Kill();
            
            var a = fadeRenderer.color.a;
            color.a = a;
            fadeRenderer.color = color;
            fadeTween = fadeRenderer.DOFade(0f, duration).SetDelay(delay);
        }
        
        // í•¸ë“œí° ì§„ë™
        public void PhoneVibration(float duration = 0.1f)
        {
            transform.DOShakePosition(duration, 0.3f, 50, 90f);
            SoundManager.Instance.GetAudioSource("Effect").PlayOneShot(vibrationSound);
        }
    }
        

    // ë Œë” í…ìŠ¤ì³
    public partial class PhoneControl
    {
        [Header("Phone View Port ê´€ë ¨")]
        public Shader phoneShader;
        public Sprite phoneVerticalSprite;
        public Sprite phoneHorizonSprite;
        
        private Dictionary<string, PhoneViewPort> phoneViewPortDictionary = new();
        [Tooltip("ìƒì„±ë  Phone View Port í”„ë¦¬í©")]public PhoneViewPort phoneViewPortPrefab;
        public PhoneViewPort currentPhoneViewPort;
        public PhoneViewType viewType;

        public PhoneViewPort GetAppViewPort(IPhoneApplication app) => phoneViewPortDictionary.GetValueOrDefault(app.AppName);

        public void PhoneViewRotate(int value) => PhoneViewRotate(value, null);
        public void PhoneViewRotate(PhoneViewType value) => PhoneViewRotate((int)value);
        public void PhoneViewRotate(PhoneViewType value, Action isRotated) => PhoneViewRotate((int)value, isRotated);
        public void PhoneViewRotate(int value, Action isRotated)
        {
            viewType = (PhoneViewType)value;

            var sequence = DOTween.Sequence();
            switch (viewType)
            {
                case PhoneViewType.Vertical:
                    sequence.Append(transform.DORotate(new Vector3(0, 0, 0), 1f).OnComplete(() =>
                    {
                        currentPhoneViewPort.horizon.SetActive(false);
                        currentPhoneViewPort.vertical.SetActive(true);
                        phoneCamera.targetTexture = currentPhoneViewPort.vertical.renderTexture;
                        isRotated?.Invoke();
                    }));
                    break;
                case PhoneViewType.Horizon:
                    sequence.Append(transform.DORotate(new Vector3(0, 0, 90), 1f).OnComplete(() =>
                    {
                        currentPhoneViewPort.vertical.SetActive(false);
                        currentPhoneViewPort.horizon.SetActive(true);
                        phoneCamera.targetTexture = currentPhoneViewPort.horizon.renderTexture;
                        isRotated?.Invoke();
                    }));
                    break;
            }
        }

        public void ChangeViewPort(PhoneViewPort viewPort)
        {
            var prevPhoneViewPort = currentPhoneViewPort;
            if (prevPhoneViewPort != viewPort)
            {
                if (prevPhoneViewPort != null)
                {
                    var currentPos = currentPhoneViewPort.transform.position;
                    currentPos.z = 10;
                    currentPhoneViewPort.transform.position = currentPos;
                }
                // ê°ì¢… ì—°ì¶œ íš¨ê³¼ë¥¼ ìœ„í•´ 0.3ì´ˆ ë’¤ì— ì´ì „ ViewPortë¥¼ ë¹„í™œì„±í™”
                Observable.Timer(TimeSpan.FromSeconds(0.3f)).Subscribe(_ =>
                {
                    if (prevPhoneViewPort != null)
                        prevPhoneViewPort.gameObject.SetActive(false);
                });
            }

            viewPort.gameObject.SetActive(true);
            viewPort.SetActive(viewType);
            phoneCamera.targetTexture = viewPort.GetData(viewType).renderTexture;
            currentPhoneViewPort = viewPort;
            isUpdateInteract = true;
        }
    }

    public partial class PhoneControl
    {
        [Header("Phone View ìƒí˜¸ì‘ìš© ê´€ë ¨")]
        private PointerEventData pointerData;
        private List<RaycastResult> rayCastResults = new List<RaycastResult>();
        private GameObject lastHoveredObject = null; // ë§ˆì§€ë§‰ìœ¼ë¡œ ë§ˆìš°ìŠ¤ë¥¼ ì˜¬ë¦° UI
        private GameObject lastPressedObject = null; // ë§ˆì§€ë§‰ìœ¼ë¡œ í´ë¦­í•œ UI
        private GameObject draggingObject = null;
        public bool isUpdateInteract = false;
        public bool isInMousePosition = true;

        public Vector2 phoneMousePosition;
        private Vector2 prevMousePosition;
        
        private void InteractInit()
        {
            pointerData = new PointerEventData(EventSystem.current);
        }

        // Phoneê³¼ Objectë“¤ì˜ ë§ˆìš°ìŠ¤ ìƒí˜¸ì‘ìš© ìš©ìœ¼ë¡œ ì‚¬ìš©í• ë•Œ
        public Vector3 ScreenToWorldPoint()
        {
            return !isUpdateInteract ? Vector2.positiveInfinity : phoneCamera.ScreenToWorldPoint(phoneMousePosition);
        }

        // UIì™€ ìƒí˜¸ì‘ìš©í• ë•Œ
        public void UIInteract()
        {
            if(isUpdateInteract == false) return;
            var curRenderData = currentPhoneViewPort.GetData(viewType); // ì„ì‹œìš©
            float unitToPixel = Screen.height / (Camera.main.orthographicSize * 2); // 1Unit ë‹¹ ëª‡ í”½ì…€ì¸ì§€
            Vector2 screenSize = new Vector2Int(Screen.width, Screen.height); // í˜„ì¬ í•´ìƒë„ í¬ê¸°
            Vector2 renderTextureSize = new(curRenderData.renderTexture.width, curRenderData.renderTexture.height); // ë Œë” í…ìŠ¤ì³ì˜ í¬ê¸°
            Vector2 spriteTextureSize = (curRenderData.spriteRenderer.sprite.rect.size / curRenderData.spriteRenderer.sprite.pixelsPerUnit) * curRenderData.spriteRenderer.transform.lossyScale * unitToPixel; // ìŠ¤í”„ë¼ì´íŠ¸ì˜ í”½ì…€ í¬ê¸° * ì˜¤ë¸Œì íŠ¸ scale
            Vector2 viewRatio = renderTextureSize / spriteTextureSize; // ë Œë” í…ìŠ¤ì³ í•´ìƒë„ : ìŠ¤í”„ë¼ì´íŠ¸ í•´ìƒë„
            Vector2 mousePosition = Mouse.current.position.ReadValue(); // ë§ˆìš°ìŠ¤ì˜ í˜„ì¬ ìœ„ì¹˜
            Vector2 objPosition = curRenderData.spriteRenderer.transform.position * unitToPixel; // ì˜¤ë¸Œì íŠ¸ì˜ í˜„ì¬ ìœ„ì¹˜ë¥¼ viewport ìœ„ì¹˜ë¡œ ì „í™˜
            // Vector2 cameraPosition = phoneCamera.transform.position * unitToPixel; // ì¹´ë©”ë¼ì˜ í˜„ì¬ ìœ„ì¹˜ë¥¼ viewport ìœ„ì¹˜ë¡œ ì „í™˜
            phoneMousePosition = (mousePosition - objPosition - screenSize / 2) * viewRatio + renderTextureSize / 2;
            isInMousePosition = false;
            if (phoneMousePosition.x < 0 || phoneMousePosition.x > renderTextureSize.x ||
                phoneMousePosition.y < 0 || phoneMousePosition.y > renderTextureSize.y)
            {
                if (!ReferenceEquals(lastHoveredObject, null))
                {
                    ExecuteEvents.Execute(lastHoveredObject, pointerData, ExecuteEvents.pointerExitHandler);
                    lastHoveredObject = null;
                }

                if (!ReferenceEquals(lastPressedObject, null))
                {
                    ExecuteEvents.ExecuteHierarchy(lastPressedObject, pointerData, ExecuteEvents.pointerUpHandler);
                    lastPressedObject = null;
                }
                if (!ReferenceEquals(draggingObject, null))
                {
                    ExecuteEvents.ExecuteHierarchy(draggingObject, pointerData, ExecuteEvents.endDragHandler); // ë“œë˜ê·¸ ì¢…ë£Œ
                    ExecuteEvents.ExecuteHierarchy(draggingObject, pointerData, ExecuteEvents.dropHandler); // ë“œë˜ê·¸ ì¢…ë£Œ
                    draggingObject = null;
                }
                return;
            }

            isInMousePosition = true;
            pointerData.position = phoneMousePosition;
            pointerData.delta = phoneMousePosition - prevMousePosition;
            prevMousePosition = phoneMousePosition;
            rayCastResults.Clear();
            EventSystem.current.RaycastAll(pointerData, rayCastResults);

            var phoneObject = rayCastResults.Where(r => r.gameObject.layer == LayerMask.NameToLayer("Phone")).ToArray();
            if (phoneObject.Length <= 0)
            {
                if (!ReferenceEquals(lastHoveredObject, null))
                {
                    // Exit ì´ë²¤íŠ¸ (ë§ˆìš°ìŠ¤ê°€ UIì—ì„œ ë²—ì–´ë‚  ë•Œ)
                    ExecuteEvents.Execute(lastHoveredObject, pointerData, ExecuteEvents.pointerExitHandler);
                    lastHoveredObject = null;
                }
                return;
            }

            pointerData.pointerCurrentRaycast = phoneObject[0];
            pointerData.pointerPressRaycast = phoneObject[0];
            var hitUI = phoneObject[0].gameObject;
            // ğŸ–±ï¸ ë§ˆìš°ìŠ¤ê°€ UI ìœ„ì— ìˆëŠ” ê²½ìš° (Hover)
            // Enter ì´ë²¤íŠ¸ (ë§ˆìš°ìŠ¤ê°€ ìƒˆë¡œ UIì— ì˜¬ë¼ê°”ì„ ë•Œ)
            var hoveredObj = ExecuteEvents.GetEventHandler<IPointerEnterHandler>(hitUI);
            if (!ReferenceEquals(hoveredObj, lastHoveredObject))
            {
                ExecuteEvents.Execute(lastHoveredObject, pointerData, ExecuteEvents.pointerExitHandler);
                lastHoveredObject = ExecuteEvents.ExecuteHierarchy(hoveredObj, pointerData, ExecuteEvents.pointerEnterHandler);
            }
            
            // ğŸ–±ï¸ ë§ˆìš°ìŠ¤ ë²„íŠ¼ì´ ëˆŒë ¸ì„ ë•Œ (Click Down)
            if (
#if ENABLE_INPUT_SYSTEM
                Mouse.current.leftButton.wasPressedThisFrame
#else
                Input.GetMouseButtonDown(0)
#endif
            )
            {
                draggingObject = ExecuteEvents.ExecuteHierarchy(hitUI, pointerData, ExecuteEvents.initializePotentialDrag);
                pointerData.pointerPress = draggingObject;
                
                var downObj = ExecuteEvents.ExecuteHierarchy(hitUI, pointerData, ExecuteEvents.pointerDownHandler);
                ExecuteEvents.Execute(downObj, pointerData, ExecuteEvents.selectHandler); // ì„ íƒ ì²˜ë¦¬
                lastPressedObject = downObj;
                pointerData.pointerPress = downObj;

                var isDragNull = ReferenceEquals(draggingObject, null);
                var isLastPressNull = ReferenceEquals(lastPressedObject, null);
                if (!isDragNull)
                {
                    ExecuteEvents.Execute(draggingObject, pointerData, ExecuteEvents.beginDragHandler);
                    ExecuteEvents.Execute(draggingObject, pointerData, ExecuteEvents.selectHandler); // ì„ íƒ ì²˜ë¦¬
                }
                // ì•„ë¬´ê²ƒë„ í´ë¦­ ëœê²Œ ì—†ìœ¼ë©´
                else if (isLastPressNull)
                {
                    SoundManager.Instance.GetAudioSource("Effect").PlayOneShot(emptyClickSound);
                }
            }

            // ğŸ–±ï¸ ë§ˆìš°ìŠ¤ ë²„íŠ¼ì„ ë–¼ì—ˆì„ ë•Œ (Click Up)
            if (
#if ENABLE_INPUT_SYSTEM
                Mouse.current.leftButton.wasReleasedThisFrame
#else
                Input.GetMouseButtonUp(0)
#endif
               )
            {
                var upObj = ExecuteEvents.ExecuteHierarchy(hitUI, pointerData, ExecuteEvents.pointerUpHandler);
                ExecuteEvents.Execute(lastPressedObject, pointerData, ExecuteEvents.pointerUpHandler);

                // í´ë¦­ì´ ê°™ì€ ì˜¤ë¸Œì íŠ¸ì—ì„œ ë°œìƒí•œ ê²½ìš° í´ë¦­ ì´ë²¤íŠ¸ ì‹¤í–‰
                if (ReferenceEquals(upObj, lastPressedObject))
                    ExecuteEvents.Execute(lastPressedObject, pointerData, ExecuteEvents.pointerClickHandler);

                lastPressedObject = null;
                pointerData.pointerPress = null;
            }

            // ğŸ–±ï¸ ë§ˆìš°ìŠ¤ ì´ë™ ì¤‘ì¼ ë•Œ (Drag)
            if (
#if ENABLE_INPUT_SYSTEM
                Mouse.current.leftButton.isPressed
#else
                Input.GetMouseButton(0)
#endif
            ) // ë§ˆìš°ìŠ¤ê°€ ëˆŒë¦° ìƒíƒœì—ì„œ
            { 
                if (!ReferenceEquals(draggingObject, null))
                {
                    pointerData.dragging = true;
                    ExecuteEvents.Execute(draggingObject, pointerData, ExecuteEvents.dragHandler); // ë“œë˜ê·¸ ì¤‘
                }
                if (!ReferenceEquals(lastPressedObject, null))
                {
                    ExecuteEvents.Execute(lastPressedObject, pointerData, ExecuteEvents.pointerMoveHandler); // ì›€ì§ì´ëŠ” ì¤‘
                }
            }
            else
            {
                if (!ReferenceEquals(draggingObject, null))
                {
                    pointerData.dragging = false;
                    ExecuteEvents.Execute(draggingObject, pointerData, ExecuteEvents.endDragHandler); // ë“œë˜ê·¸ ì¢…ë£Œ
                    ExecuteEvents.Execute(draggingObject, pointerData, ExecuteEvents.dropHandler); // ë“œë˜ê·¸ ì¢…ë£Œ
                    draggingObject = null;
                }

                lastPressedObject = null;
            }
        }
    }
}